services:
    _defaults:
        autowire: true
        autoconfigure: true

    vardumper\IbexaFormBuilderBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/IbexaFormBuilderBundle.php'
