ibexa:
    system:
        site:
            content_view:
                full:
                    form_builder_horizontal_group:
                        template: '@IbexaFormBuilderBundle/form/horizontal_group.html.twig'
                        match:
                            Identifier\ContentType: form_builder_horizontal_group
        admin_group:
            content_type:
                form_builder_form:
                    thumbnail: /bundles/ibexaformbuilder/icons/form.svg
                form_builder_input:
                    thumbnail: /bundles/ibexaformbuilder/icons/form-input.svg
                form_builder_textarea:
                    thumbnail: /bundles/ibexaformbuilder/icons/textbox.svg
                form_builder_select:
                    thumbnail: /bundles/ibexaformbuilder/icons/icons-sprite.svg#select
                form_builder_option:
                    thumbnail: /bundles/ibexaformbuilder/icons/icons-sprite.svg#option
                form_builder_fieldset:
                    thumbnail: /bundles/ibexaformbuilder/icons/folder.svg
                form_builder_horizontal_group:
                    thumbnail: /bundles/ibexaformbuilder/icons/group.svg
                form_builder_button:
                    thumbnail: /bundles/ibexaformbuilder/icons/enter.svg
                form_builder_choice:
                    thumbnail: /bundles/ibexaformbuilder/icons/icons-sprite.svg#choice
